import type { VirtualFS } from '../../filesystem.js';
import type { GameState } from '../GameState.js';
import type { CommandResult } from './index.js';

const MAN_PAGES: Record<string, string[]> = {
	sa: [
		"SA(8)                   System Manager's Manual                  SA(8)",
		'',
		'NAME',
		'     sa -- print system accounting statistics',
		'',
		'SYNOPSIS',
		'     sa [-abcdDfijkKlmnrstu] [file]',
		'',
		'DESCRIPTION',
		'     The sa command reports on, cleans up, and generally maintains system',
		'     accounting files.  It will condense the information in /var/account/acct',
		'     into a summary file /var/account/savacct.',
		'',
		'     Output columns:',
		'       re   real time (wall clock seconds)',
		'       cp   CPU time (user + system)',
		'       avio average number of I/O operations per execution',
		'       k    average kcore-minutes',
		'',
		'     CPU time is the basis for billable compute charges.',
		'',
		'SEE ALSO',
		'     lastcomm(1), acct(5)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	last: [
		'LAST(1)                  User Commands                   LAST(1)',
		'',
		'NAME',
		'     last -- indicate last logins of users',
		'',
		'SYNOPSIS',
		'     last [-N] [name ...]',
		'',
		'DESCRIPTION',
		'     Last will list the sessions of specified users, ttys, and hosts,',
		'     in reverse time order.  Each line of output contains the user name,',
		'     the tty from which the session was conducted, any hostname, the',
		'     start and stop times for the session, and the duration.',
		'',
		'     If no user is given, last lists sessions for all users.',
		'',
		'     The pseudo-user reboot logs in each time the system is rebooted.',
		'',
		'SEE ALSO',
		'     lastcomm(1), utmp(5)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	lastcomm: [
		'LASTCOMM(1)              User Commands                LASTCOMM(1)',
		'',
		'NAME',
		'     lastcomm -- show last commands executed, in reverse order',
		'',
		'SYNOPSIS',
		'     lastcomm [command name] ... [user name] ... [terminal name] ...',
		'',
		'DESCRIPTION',
		'     Lastcomm gives information on previously executed commands.  With no',
		'     arguments, lastcomm prints information on all commands recorded.',
		'',
		'     For each process entry, lastcomm shows:',
		'       - command name',
		'       - flags (S = SUID, F = command forked but did not exec)',
		'       - user who ran the command',
		'       - tty the command was run on',
		'       - CPU time consumed',
		'       - date and time the command was run',
		'',
		'     Flags of note:',
		'       S   SUID bit was set -- command ran with elevated privileges',
		'       F   command forked without exec (unusual)',
		'',
		'SEE ALSO',
		'     sa(8), last(1), acct(5)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	finger: [
		'FINGER(1)                User Commands                 FINGER(1)',
		'',
		'NAME',
		'     finger -- user information lookup program',
		'',
		'SYNOPSIS',
		'     finger [-lmsp] [user ...]',
		'',
		'DESCRIPTION',
		'     The finger utility displays information about the system users.',
		'',
		'     For each user listed, finger displays:',
		'       - login name',
		'       - real name (from GECOS field of /etc/passwd)',
		'       - home directory and login shell',
		'       - last login time and terminal',
		'       - contents of .plan and .project files if present',
		'',
		'     With no arguments, finger lists all users currently logged in.',
		'',
		'SEE ALSO',
		'     who(1), last(1), passwd(5)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	grep: [
		'GREP(1)                  User Commands                   GREP(1)',
		'',
		'NAME',
		'     grep -- file pattern searcher',
		'',
		'SYNOPSIS',
		'     grep [-iclnv] pattern [file ...]',
		'',
		'DESCRIPTION',
		'     The grep utility searches any given input files, selecting lines that',
		'     match one or more patterns.  By default, grep is case sensitive.',
		'',
		'     Useful flags:',
		'       -i   case insensitive matching',
		'       -n   print line numbers',
		'       -l   only print file names with matches',
		'       -v   invert match (print non-matching lines)',
		'',
		'SEE ALSO',
		'     egrep(1), fgrep(1)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	who: [
		'WHO(1)                   User Commands                    WHO(1)',
		'',
		'NAME',
		'     who -- display who is on the system',
		'',
		'SYNOPSIS',
		'     who [-mTu] [am i]',
		'',
		'DESCRIPTION',
		'     The who utility displays a list of all users currently logged in,',
		'     showing their login name, terminal line, and login time.',
		'',
		'SEE ALSO',
		'     finger(1), last(1), w(1)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	ps: [
		'PS(1)                    User Commands                     PS(1)',
		'',
		'NAME',
		'     ps -- process status',
		'',
		'SYNOPSIS',
		'     ps [-aAcefhjlmrSTuvwx] [-G group] [-o fmt] [-p pid] [-t tty] [-U user]',
		'',
		'DESCRIPTION',
		'     The ps utility displays a header line followed by lines containing',
		'     information about all your processes that have controlling terminals.',
		'',
		'     Columns: USER PID %CPU %MEM TIME COMMAND',
		'',
		'SEE ALSO',
		'     kill(1), top(1)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	mail: [
		'MAIL(1)                  User Commands                   MAIL(1)',
		'',
		'NAME',
		'     mail -- send and receive mail',
		'',
		'SYNOPSIS',
		'     mail [-iInv] [-s subject] [-c cc-addr] [-b bcc-addr] to-addr ...',
		'     mail [-iInNv] -f [name]',
		'',
		'DESCRIPTION',
		'     Mail is an intelligent mail processing system with a command syntax',
		'     similar to ed(1).  Commands are typed after the ? prompt.',
		'',
		'     When reading mail:',
		'       p        print current message',
		'       n        next message',
		'       d        delete current message',
		'       r        reply to current message',
		'       q        quit',
		'       ?        help',
		'',
		'SEE ALSO',
		'     sendmail(8), aliases(5)',
		'',
		'4.3 Berkeley Distribution         June 5, 1986',
	],
	nmap: ['nmap: command not found', '', '(This tool does not exist on this system.)'],
};

export function handleMan(_args: string[], _state: GameState, _vfs: VirtualFS): CommandResult {
	const topic = _args[0];

	if (!topic) {
		return { type: 'lines', lines: ['usage: man command'] };
	}

	const lower = topic.toLowerCase();

	if (lower === 'nmap') {
		return { type: 'lines', lines: MAN_PAGES.nmap };
	}

	const page = MAN_PAGES[lower];
	if (!page) {
		return { type: 'lines', lines: [`No manual entry for ${topic}`] };
	}

	return { type: 'lines', lines: page };
}
